flags:
  isCommandsEnabled: true
  commands:
    isCommandEnabled: true
    isDiffDirectoryEnabled: false
    isDiffFilesEnabled: false
    isListingEnabled: false
    isChecksumEnabled: true
    isProcessesEnabled: false
    isSshEnabled: false
  isMariaDBServiceEnabled: false

configDirectory: PROD

appCode: ${appCode}
serviceCode: ${serviceCode}




