sh-commands:
  commands:
    - java --version
    - python --version
    - rm text
  directories:
    - /script/directory1, /script/directory2
  files:
    - /script/file1, /script/file2
  checksums:
    - /script/file1, /script/file2
  processes:
    - test.jar
  listings:
    -/script/folder1
  ssh:
    -server@name
